# This workflow will build the package and then upload to PyPI or TestPyPI.
# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# for more information.

name: build-and-publish

on:
  # allow manually activating the workflow; for manual runs, can select uploading
  # to testpypi first to check if the release works
  workflow_dispatch:
    inputs:
        destination:
          description: The PyPI site to upload to, or None
          required: true
          type: choice
          options: ["none", "testpypi", "pypi"]

  release:
    types: [published]

# cancel current jobs if a new job is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      # fetch-depth: '0' is needed to fetch tags for hatch-vcs (and thus setuptools-scm)
      # in order to generate the version correctly
      with:
        fetch-depth: '0'
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.13'

    - name: Build wheel and sdist
      run: |
        python -m pip install --upgrade pip build
        python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: python-package-distribution
        path: dist/

  publish-to-pypi:

    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.destination == 'pypi') || (github.event_name == 'release' && github.event.action == 'published')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pybaselines
    permissions:
      id-token: write  # required for trusted publishing

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: python-package-distribution
        path: dist/

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        print-hash: true

  publish-to-testpypi:

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.destination == 'testpypi'
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pybaselines
    permissions:
      id-token: write  # required for trusted publishing

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: python-package-distribution
        path: dist/

    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        repository-url: https://test.pypi.org/legacy/
        print-hash: true
